config/routes.rb
Nix::Application.routes.draw do
  get "dashboard/index"

  devise_for :users

  scope "/admin" do
    resources :users, :roles
  end
  post 'suppliers/generate_spot_plan' => 'suppliers#generate_spot_plan', as: :generate_spot_plan
  post 'suppliers/generate_spot_plan_template' => 'suppliers#generate_spot_plan_template', as: :generate_spot_plan_template
  get 'suppliers/upload_spot_plan' => 'suppliers#upload_spot_plan', as: :upload_spot_plan
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/start' => 'projects#start', as: :start_project
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/save_project_users' => 'projects#save_project_users', as: :save_project_users
  get 'clients/:id/assign_user' => 'clients#assign_user', as: :assign_client_user
  post 'clients/:id/save_client_users' => 'clients#save_client_users', as: :save_client_users
  post 'orders/:id/finish' => 'orders#finish', as: :finish_order
  post 'projects/download_project_info/:id' => 'projects#download_project_info', as: :download_project_info
  post 'web_site_media_reporters/download_reporter_info' => 'web_site_media_reporters#download_reporter_info', as: :download_reporter_info
  get 'web_site_media_reporters/upload_reporter_info' => 'web_site_media_reporters#upload_reporter_info', as: :upload_reporter_info
  post 'fashion_media_infos/download_media_info' => 'fashion_media_infos#download_media_info', as: :download_media_info
  get 'fashion_media_infos/upload_media_info' => 'fashion_media_infos#upload_media_info', as: :upload_media_info
  post 'traveling_photography_media_infos/download_traveling_photography_media_info' => 'traveling_photography_media_infos#download_traveling_photography_media_info', as: :download_traveling_photography_media_info
  get 'traveling_photography_media_infos/upload_traveling_photography_media_info' => 'traveling_photography_media_infos#upload_traveling_photography_media_info', as: :upload_traveling_photography_media_info
  post 'network_opinion_leader_bloggers/download_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#download_network_opinion_leader_blogger', as: :download_network_opinion_leader_blogger
  get 'network_opinion_leader_bloggers/upload_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#upload_network_opinion_leader_blogger', as: :upload_network_opinion_leader_blogger
  post 'grass_resources/download_grass_resource' => 'grass_resources#download_grass_resource', as: :download_grass_resource
  get 'grass_resources/upload_grass_resource' => 'grass_resources#upload_grass_resource', as: :upload_grass_resource
  post 'grass_resources/download_grass_resource_template' => 'grass_resources#download_grass_resource_template', as: :download_grass_resource_template
  post 'moderators/download_moderator' => 'moderators#download_moderator', as: :download_moderator
  get 'moderators/upload_moderator' => 'moderators#upload_moderator', as: :upload_moderator
  get 'file_categories/upload_file_category' => 'file_categories#upload_file_category', as: :upload_file_category
  post 'file_categories/download_file/:id' => 'file_categories#download_file', as: :download_file

  resources :business_categories do
    resources :suppliers
  end
  resources :clients do
    resources :projects do
      resources :orders
    end
  end
  resources :projects do
    resources :file_categories
  end

  resources :suppliers do
    resources :supplier_evaluations
  end
  resources :suppliers,:clients,:projects,:orders,:departments,:network_opinion_leader_bloggers,:moderators,:grass_resources
  resources :business_categories,:supplier_evaluations,:web_site_media_reporters,:fashion_media_infos,:traveling_photography_media_infos,:specifications
  root to: 'dashboard#index', as: :dashboard

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/fashion_media_infos_controller.rb
class FashionMediaInfosController < ApplicationController

  before_filter :has_login
  add_breadcrumb(I18n.t('model.list', model: FashionMediaInfo.model_name.human), :fashion_media_infos_path, except: :index)
  def index
    sql,sql_attr=' deleted=0',[]

    unless params[:web_site].blank?
      sql += " and web_site like ? "
      sql_attr << "%"+params[:web_site]+"%"
    end

    unless params[:content_name].blank?
      sql += " and content_name like ? "
      sql_attr << "%"+params[:content_name]+"%"
    end

    unless params[:position].blank?
      sql += " and position like ? "
      sql_attr << "%"+params[:position]+"%"
    end

    unless params[:mobile].blank?
      sql += " and mobile like ? "
      sql_attr << "%"+params[:mobile]+"%"
    end

    unless params[:email].blank?
      sql += " and email like ? "
      sql_attr << "%"+params[:email]+"%"
    end

    unless params[:coverage].blank?
      sql += " and coverage >= ? "
      sql_attr << params[:coverage].to_f
    end

    unless params[:coverage1].blank?
      sql += " and coverage <= ? "
      sql_attr << params[:coverage1].to_f
    end


    @medias_grid = initialize_grid(FashionMediaInfo.where([sql]+sql_attr))
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medias_grid }
    end
  end

  def new
    @media = FashionMediaInfo.new()
    @media.created_by = current_user.id
    @cities = City.all(:order=>'CONVERT(name USING gbk)')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @media }
    end
  end

  def create
    @media = FashionMediaInfo.new(params[:fashion_media_info])

    #@project.assigned_users << current_user
    @media.updated_by = current_user.id
    @media.created_by = current_user.id

    respond_to do |format|
      if @media.other_valid? and @media.save
        format.html { redirect_to fashion_media_infos_path, notice: "成功创建#{FashionMediaInfo.model_name.human}" }
        format.json { render json: @media, status: :created, location: @media }
      else
        @cities = City.all(:order=>'CONVERT(name USING gbk)')
        format.html { render action: "new" }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @media = FashionMediaInfo.find(params[:id])
    @cities = City.all(:order=>'CONVERT(name USING gbk)')
  end

  def update
    @media = FashionMediaInfo.find(params[:id])
    @media.attributes = params[:fashion_media_info]
    @media.updated_by = current_user.id
    respond_to do |format|
      if @media.other_valid? and @media.save
        format.html { redirect_to fashion_media_infos_path, notice: "成功修改#{FashionMediaInfo.model_name.human}" }
        format.json { head :no_content }
      else
        @cities = City.all(:order=>'CONVERT(name USING gbk)')
        format.html { render action: "edit" }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @media = FashionMediaInfo.find(params[:id])
    @media.deleted=1

    if @media.save
      respond_to do |format|
        format.html { redirect_to fashion_media_infos_path, notice: "成功删除#{FashionMediaInfo.model_name.human}" }
        format.json { head :no_content }
      end
    end
  end

  def download_media_info
    sql,sql_attr=' deleted=0',[]

    unless params[:web_site].blank?
      sql += " and web_site like ? "
      sql_attr << "%"+params[:web_site]+"%"
    end

    unless params[:content_name].blank?
      sql += " and content_name like ? "
      sql_attr << "%"+params[:content_name]+"%"
    end

    unless params[:position].blank?
      sql += " and position like ? "
      sql_attr << "%"+params[:position]+"%"
    end

    unless params[:mobile].blank?
      sql += " and mobile like ? "
      sql_attr << "%"+params[:mobile]+"%"
    end

    unless params[:email].blank?
      sql += " and email like ? "
      sql_attr << "%"+params[:email]+"%"
    end

    unless params[:coverage].blank?
      sql += " and coverage >= ? "
      sql_attr << params[:coverage].to_f
    end

    unless params[:coverage1].blank?
      sql += " and coverage <= ? "
      sql_attr << params[:coverage1].to_f
    end


    data = FashionMediaInfo.where([sql]+sql_attr)
    new_file = FashionMediaInfo.create_new_template(data)
    send_file new_file, :type => "application/octet-stream", :disposition => "attachment"
  end

  def upload_media_info
    if request.post?
      if params[:excel_file].blank?
        render :text => "<script>alert('请选择上传的文件!');history.go(-1);</script>"
      else
        if %w(xls).include?(params[:excel_file].original_filename.to_s.split('.')[-1])
          begin
            new_file_name = upload_file(params[:excel_file], "/public/files/temp/")
            workbook = Spreadsheet.open("#{Rails.root}/public/files/temp/"+new_file_name)

            _sheet = workbook.worksheet(0)
            _error_info = FashionMediaInfo.create_by_excel(_sheet,current_user)
            FileUtils.rm Dir["#{Rails.root}/public/files/temp/*.xls"]
            respond_to do |format|
              if _error_info == ''
                format.html { redirect_to fashion_media_infos_path(), notice: '上传完成！！！' }
                format.json { render json: {}, status: :created, location: {} }
              else
                format.html { redirect_to fashion_media_infos_path(), alert: _error_info }
                format.json { render json: {}, status: :created, location: {} }
              end
            end

          rescue Exception => e
            ActiveRecord::Rollback
            render :text => "<script>alert('#{e.to_s}');history.go(-1);</script>"
            return
          end
        else
          render :text => "<script>alert('格式错误!');history.go(-1);</script>"
        end
      end
    end
  end
end

app/helpers/fashion_media_infos_helper.rb
module FashionMediaInfosHelper
end

app/views/fashion_media_infos/edit.html.erb
<div class="narrow-center-page">

  <%= render_cell(
              :page_title,
              :show,
              data:
                      {
                              name: "#{t('model.edit', model: FashionMediaInfo.model_name.human)} <small>#{t('simple_form.required.text') }</small>",
                              toolbar: {
                                      left:
                                              [
                                                      render_cell(
                                                              :button,
                                                              :show,
                                                              data:
                                                                      {
                                                                              name: fa_icon('level-up rotate-270'),
                                                                              url: fashion_media_infos_path,
                                                                              options:
                                                                                      {
                                                                                              class: 'btn',
                                                                                              rel: 'tooltip',
                                                                                              title: "#{t('labels.back_to')}#{t('model.list', :model => FashionMediaInfo.model_name.human)}",
                                                                                      }
                                                                      }
                                                      )
                                              ]
                              }
                      }
      )
  %>

  <%= simple_form_for(@media , :html => {:class => 'form-horizontal' }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">

        <%= f.input :city_id, required: false,:as=>:select,:collection=> @cities.map{|x| [x.name,x.id]}%>
        <%= f.input :web_site, required: true %>
        <%= f.input :web_site_introduction, required: true,:as=>:text,input_html: { rows: 5 } %>
        <%= f.input :content_name, required: true %>
        <%= f.input :position, required: true %>
        <%= f.input :mobile, required: false %>
        <%= f.input :email, required: false %>
        <%= f.input :qq, required: false %>
        <%= f.input :address, required: true,:as=>:text,input_html: { rows: 5 } %>
        <%= f.input :coverage, required: true %>
        <%= f.input :man, required: true %>
        <%= f.input :woman, required: true %>


        <%= f.input :notes, required: false ,:as=>:text,input_html: { rows: 5 }%>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
  <% end %>


</div>

app/views/fashion_media_infos/index.html.erb
<%= form_tag({},:method=>'get',:id=>'commit_form') do -%>
<%= render_cell(:page_title, :show, data:{name: "#{t('model.list', model: FashionMediaInfo.model_name.human)}",
                                          toolbar: {
                                                  right:
                                                          [
                                                                  (render_cell(:button, :show, data:
                                                                          {
                                                                                  name: fa_icon('plus-sign', text: t('model.create', :model => FashionMediaInfo.model_name.human)),
                                                                                  url: new_fashion_media_info_path,
                                                                                  options: {class: 'btn btn-primary'}
                                                                          }) if can? :create,FashionMediaInfo),
                                                                  (render_cell(
                                                                          :button,
                                                                          :show,
                                                                          data:
                                                                                  {
                                                                                          name: fa_icon('cloud-upload', text: t('model.upload', model: FashionMediaInfo.model_name.human)),
                                                                                          url: upload_media_info_path,
                                                                                          options: {class: 'btn btn-success'}
                                                                                  }
                                                                  ) if can? :update,FashionMediaInfo or can? :create,FashionMediaInfo),
                                                                  render_cell(:button, :show,
                                                                              data:
                                                                                      {
                                                                                              name: fa_icon('download-alt', text: t('model.download',:model => FashionMediaInfo.model_name.human)),
                                                                                              url: download_media_info_path(params),
                                                                                              options:
                                                                                                      {
                                                                                                              class: 'btn btn-info',
                                                                                                              method: :post
                                                                                                      }
                                                                                      }
                                                                  )

                                                          ]
                                          }
})
%>

<div class="well">
      网站：
      <%= text_field_tag 'web_site',params[:web_site],:style=>"width:100px"-%>
      联系人:
      <%= text_field_tag 'content_name',params[:content_name],:style=>"width:60px"-%>
      职位:
      <%= text_field_tag 'position',params[:position],:style=>"width:100px"-%>
      电话:
      <%= text_field_tag 'mobile',params[:mobile],:style=>"width:100px"-%>
      邮箱:
      <%= text_field_tag 'email',params[:email],:style=>"width:100px"-%>
      日均覆盖人数:
      <%= text_field_tag 'coverage',params[:coverage],:style=>"width:50px"-%>万人 到
      <%= text_field_tag 'coverage1',params[:coverage1],:style=>"width:50px"-%>万人
      <%= submit_tag('查询') -%>

</div>
  <% end -%>
<%= grid(@medias_grid, :show_filters => :when_filtered,:class=> 'tablestyle') do |g|

  g.column name: t('activerecord.attributes.fashion_media_info.city_id') do |m|
    m.city_name
  end
  g.column name: t('activerecord.attributes.fashion_media_info.web_site') do |m|
    m.web_site
  end
  g.column name: t('activerecord.attributes.fashion_media_info.web_site_introduction'),:class=>'td_style' do |m|
    m.web_site_introduction
  end
  g.column name: t('activerecord.attributes.fashion_media_info.content_name') do |m|
    m.content_name
  end
  g.column name: t('activerecord.attributes.fashion_media_info.position') do |m|
    m.position
  end
  g.column name: t('activerecord.attributes.fashion_media_info.mobile') do |m|
    m.mobile
  end
  g.column name: t('activerecord.attributes.fashion_media_info.email') do |m|
    m.email
  end
  g.column name: t('activerecord.attributes.fashion_media_info.qq') do |m|
    m.qq
  end
  g.column name: t('activerecord.attributes.fashion_media_info.address') do |m|
    m.address
  end
  g.column name: t('activerecord.attributes.fashion_media_info.coverage') do |m|
    m.coverage
  end
  g.column name: t('activerecord.attributes.fashion_media_info.man') do |m|
    m.man
  end
  g.column name: t('activerecord.attributes.fashion_media_info.woman') do |m|
    m.woman
  end
  g.column name: t('activerecord.attributes.fashion_media_info.notes') do |m|
    m.notes
  end


  g.column name: t('activerecord.attributes.fashion_media_info.updated_by') do |m|
    m.updated_name
  end

  g.column name: t('activerecord.attributes.fashion_media_info.created_by') do |m|
    m.created_name
  end

  if can? :update,FashionMediaInfo
    g.column html: {class: 'btn-cell'} do |p|
      link_to(fa_icon('edit'), edit_fashion_media_info_path(p), :class => 'btn', :rel => 'tooltip', :title => t('buttons.edit'))
    end
  end

  if can? :destroy,FashionMediaInfo
    g.column html: {class: 'btn-cell'} do |p|
      link_to(fa_icon('trash'), fashion_media_info_path(p), :method => :delete, :confirm => t("confirms.delete"), :class => 'btn btn-danger', :rel => 'tooltip', :title => t('buttons.delete'))
    end
  end





end -%>
<style type="text/css">
    .tablestyle{
        width: 3000px;
    }

    #grid{
        overflow: auto;

    }
    .td_style{
        width: 750px;
    }

</style>
<script>
  $('#grid').attr('style','height:300px');
</script>

app/views/fashion_media_infos/new.html.erb
<div class="narrow-center-page">

  <%= render_cell(
              :page_title,
              :show,
              data:
                      {
                              name: "#{t('model.create', model: FashionMediaInfo.model_name.human)} <small>#{t('simple_form.required.text') }</small>",
                              toolbar: {
                                      left:
                                              [
                                                      render_cell(
                                                              :button,
                                                              :show,
                                                              data:
                                                                      {
                                                                              name: fa_icon('level-up rotate-270'),
                                                                              url: fashion_media_infos_path,
                                                                              options:
                                                                                      {
                                                                                              class: 'btn',
                                                                                              rel: 'tooltip',
                                                                                              title: "#{t('labels.back_to')}#{t('model.list', :model => FashionMediaInfo.model_name.human)}",
                                                                                      }
                                                                      }
                                                      )
                                              ]
                              }
                      }
      )
  %>

  <%= simple_form_for(@media , :html => {:class => 'form-horizontal' }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">

      <%= f.input :city_id, required: false,:as=>:select,:collection=> @cities.map{|x| [x.name,x.id]}%>
      <%= f.input :web_site, required: true %>
      <%= f.input :web_site_introduction, required: true,:as=>:text,input_html: { rows: 5 } %>
      <%= f.input :content_name, required: true %>
      <%= f.input :position, required: true %>
      <%= f.input :mobile, required: false %>
      <%= f.input :email, required: false %>
      <%= f.input :qq, required: false %>
      <%= f.input :address, required: true,:as=>:text,input_html: { rows: 5 } %>
      <%= f.input :coverage, required: true %>
      <%= f.input :man, required: true %>
      <%= f.input :woman, required: true %>




      <%= f.input :notes, required: false ,:as=>:text,input_html: { rows: 5 }%>
        </div>
      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
  <% end %>


</div>

app/views/fashion_media_infos/upload_media_info.html.erb
<div class="narrow-center-page">

  <%= render_cell(
              :page_title,
              :show,
              data:
                      {
                              name: "<strong>#{}</strong> #{t('model.upload', model: FashionMediaInfo.model_name.human)} ",
                              toolbar:
                                      {
                                              left:
                                                      [
                                                              render_cell(
                                                                      :button,
                                                                      :show,
                                                                      data:
                                                                              {
                                                                                      name: fa_icon('level-up rotate-270'),
                                                                                      url: fashion_media_infos_path,
                                                                                      options:
                                                                                              {
                                                                                                      class: 'btn',
                                                                                                      rel: 'tooltip',
                                                                                                      title: "#{t('labels.back_to')}#{t('model.list', :model => FashionMediaInfo.model_name.human)}",
                                                                                              }
                                                                              }
                                                              )
                                                      ],
                                              right:
                                                      [

                                                      ]
                                      }
                      }
      ) %>
  <%= form_tag({:controller => :fashion_media_infos, :action => "upload_media_info"}, :multipart => true, :class => "simple_form form-horizontal upload-spot-plan-excel-file-form", :id=> "new_spot_plan_excel_file", :method=>"post",:novalidate=>"novalidate") do -%>
      <div class="form-inputs">
        <div class="control-group file optional spot_plan_excel_file_data_file"><label class="file optional control-label" for="spot_plan_excel_file_data_file">上传文件</label><div class="controls"><input class="file optional" id="excel_file" name="excel_file" type="file"></div></div>
      </div>
      <div class="form-actions">
        <input class="btn btn btn-primary" name="commit" type="submit" value="确定">
      </div>
  <% end%>




</div>

<% content_for :js do %>
    <script language='javascript'>
        $(document).ready(function(){
            $('form.upload-spot-plan-excel-file-form').on('ajax:beforeSend', function(xhr, settings) {
                $('#upload-spot-plan-excel-file-modal-window').modal({
                    backdrop: 'static',
                    keyboard: false
                });
            });

            $('form.upload-spot-plan-excel-file-form').on('ajax:complete', function(xhr, status) {
                $('#upload-spot-plan-excel-file-modal-window').modal('hide');
            });
        });
    </script>
<% end %>

<% content_for :anything_else do %>
    <div class="modal hide fade" id="upload-spot-plan-excel-file-modal-window">
      <div class="modal-header">
        <h4>正在上传...</h4>
      </div>
      <div class="modal-body">
        <div class="progress progress-striped active">
          <div class="bar" style="width: 100%;" id="modal-progress-bar"><span id="model-progress-value">请等待...</span></div>
        </div>
      </div>
    </div>
<% end %>