config/routes.rb
Nix::Application.routes.draw do
  get "dashboard/index"

  devise_for :users

  scope "/admin" do
    resources :users, :roles
  end
  post 'suppliers/generate_spot_plan' => 'suppliers#generate_spot_plan', as: :generate_spot_plan
  post 'suppliers/generate_spot_plan_template' => 'suppliers#generate_spot_plan_template', as: :generate_spot_plan_template
  get 'suppliers/upload_spot_plan' => 'suppliers#upload_spot_plan', as: :upload_spot_plan
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/start' => 'projects#start', as: :start_project
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/save_project_users' => 'projects#save_project_users', as: :save_project_users
  get 'clients/:id/assign_user' => 'clients#assign_user', as: :assign_client_user
  post 'clients/:id/save_client_users' => 'clients#save_client_users', as: :save_client_users
  post 'orders/:id/finish' => 'orders#finish', as: :finish_order
  post 'projects/download_project_info/:id' => 'projects#download_project_info', as: :download_project_info
  post 'web_site_media_reporters/download_reporter_info' => 'web_site_media_reporters#download_reporter_info', as: :download_reporter_info
  get 'web_site_media_reporters/upload_reporter_info' => 'web_site_media_reporters#upload_reporter_info', as: :upload_reporter_info
  post 'fashion_media_infos/download_media_info' => 'fashion_media_infos#download_media_info', as: :download_media_info
  get 'fashion_media_infos/upload_media_info' => 'fashion_media_infos#upload_media_info', as: :upload_media_info
  post 'traveling_photography_media_infos/download_traveling_photography_media_info' => 'traveling_photography_media_infos#download_traveling_photography_media_info', as: :download_traveling_photography_media_info
  get 'traveling_photography_media_infos/upload_traveling_photography_media_info' => 'traveling_photography_media_infos#upload_traveling_photography_media_info', as: :upload_traveling_photography_media_info
  post 'network_opinion_leader_bloggers/download_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#download_network_opinion_leader_blogger', as: :download_network_opinion_leader_blogger
  get 'network_opinion_leader_bloggers/upload_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#upload_network_opinion_leader_blogger', as: :upload_network_opinion_leader_blogger
  post 'grass_resources/download_grass_resource' => 'grass_resources#download_grass_resource', as: :download_grass_resource
  get 'grass_resources/upload_grass_resource' => 'grass_resources#upload_grass_resource', as: :upload_grass_resource
  post 'grass_resources/download_grass_resource_template' => 'grass_resources#download_grass_resource_template', as: :download_grass_resource_template
  post 'moderators/download_moderator' => 'moderators#download_moderator', as: :download_moderator
  get 'moderators/upload_moderator' => 'moderators#upload_moderator', as: :upload_moderator
  get 'file_categories/upload_file_category' => 'file_categories#upload_file_category', as: :upload_file_category
  post 'file_categories/download_file/:id' => 'file_categories#download_file', as: :download_file

  resources :business_categories do
    resources :suppliers
  end
  resources :clients do
    resources :projects do
      resources :orders
    end
  end
  resources :projects do
    resources :file_categories
  end

  resources :suppliers do
    resources :supplier_evaluations
  end
  resources :suppliers,:clients,:projects,:orders,:departments,:network_opinion_leader_bloggers,:moderators,:grass_resources
  resources :business_categories,:supplier_evaluations,:web_site_media_reporters,:fashion_media_infos,:traveling_photography_media_infos,:specifications
  root to: 'dashboard#index', as: :dashboard

  match ':controller(/:action(/:id))(.:format)'
end

app/models/business_category.rb
class BusinessCategory < ActiveRecord::Base
	has_and_belongs_to_many :suppliers
	attr_accessible :name_cn,:parent_id,:created_by,:updated_by,:is_show
  belongs_to :created_man, :class_name => "User", :foreign_key => "created_by"
  belongs_to :updated_man, :class_name => "User", :foreign_key => "updated_by"
  belongs_to :parent_category, :class_name => "BusinessCategory", :foreign_key => "parent_id"
  has_many :specifications
  validates :name_cn, presence:{message:'名称不能为空'}
  # attr_accessible :title, :body

  def self.first_categories
  	b = BusinessCategory.where('parent_id=0').order('id desc')
  	b==nil ? [] : b
  end
  def self.second_categories
    fir_cat_ids = [0]
    fir_cats = BusinessCategory.first_categories
    fir_cat_ids = fir_cats.map{|x| x.id} unless fir_cats.blank?
    b = BusinessCategory.where(['parent_id in (?)',fir_cat_ids]).order('id desc')
  	b==nil ? [] : b
  end

  def self.specs
    fir_cat_ids = [0]
    item = []
    fir_cats = BusinessCategory.first_categories
    fir_cat_ids = fir_cats.map{|x| x.id} unless fir_cats.blank?
    bs = BusinessCategory.where(['parent_id in (?)',fir_cat_ids]).order('id desc')
    unless bs.blank?
      bs.each do |b|
        b_children = b.children
        unless b_children.blank?
          b_children.each do |bc|
            item << [b.name_cn.to_s+"-"+bc.name_cn.to_s,bc.id]
          end
        end
      end
    end
    item
  end
  def children
  	bs = BusinessCategory.where('parent_id=?',self.id).order('id desc')
  	bs.blank? ? [] : bs
  end
  def cat_ids
    bs = BusinessCategory.where('parent_id=?',self.id)
    bs.blank? ? [self.id] : ([self.id]+bs.map{|b|b.id})
  end
  def get_price(supplier_id=0,show_type='￥')
    return '' if supplier_id==0
    bs = BusinessCategorySupplier.where('business_category_id=? and supplier_id= ?',self.id,supplier_id).first()
    return '--' if bs.blank?
    bs.price.to_s.blank? ? '未填写报价' : show_type+bs.price.to_s
  end
    def get_price1(supplier_id=0,show_type='￥')
    return '' if supplier_id==0
    bs = BusinessCategorySupplier.where('business_category_id=? and supplier_id= ?',self.id,supplier_id).first()
    return '' if bs.blank?
    bs.price.to_s.blank? ? '未填写报价' : show_type+bs.price.to_s
  end

  def self.show_categories
    b = BusinessCategory.where('is_show=1').order('id desc')
    b==nil ? [] : b
  end

  def created_name
    self.created_man.blank? ? '' : self.created_man.name
  end
   def updated_name
    self.updated_man.blank? ? '' : self.updated_man.name
  end
  def name
    self.name_cn
  end
  def parent_name
    self.parent_category.blank? ? '--' : self.parent_category.name_cn
  end
end

app/controllers/business_categories_controller.rb
class BusinessCategoriesController < ApplicationController
  before_filter :has_login
		add_breadcrumb(I18n.t('model.list', model: BusinessCategory.model_name.human), :business_categories_path)

  def index
    fir_cat_ids = [0]
    fir_cats = BusinessCategory.first_categories
    fir_cat_ids = fir_cats.map{|x| x.id} unless fir_cats.blank?
    @business_categories = initialize_grid(BusinessCategory.where(['parent_id in (?)',fir_cat_ids]))

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @business_categories }
    end
  end

  def new
    @business_category = BusinessCategory.new
    @first_categories = BusinessCategory.where('parent_id=0')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business_category}
    end
  end

  def edit
    @business_category = BusinessCategory.find(params[:id])
    @first_categories = BusinessCategory.where('parent_id=0')
  end

  def update
    @first_categories = BusinessCategory.where('parent_id=0')
    @business_category = BusinessCategory.find(params[:id])
    params[:business_category][:updated_by]=current_user.id
    @business_category.attributes = params[:business_category]
    respond_to do |format|
      if @business_category.save
        format.html { redirect_to business_categories_path(), notice: 'BusinessCategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @business_category = BusinessCategory.find(params[:id])
    @business_category.destroy
    Specification.delete_all('business_category_id=?',@business_category.id)
    respond_to do |format|
      format.html { redirect_to business_categories_path }
      format.json { head :no_content }
    end
  end

  def create
    params[:business_category][:created_by]=current_user.id
    params[:business_category][:updated_by]=current_user.id
    @first_categories = BusinessCategory.where('parent_id=0')
    @business_category = BusinessCategory.new(params[:business_category])

    respond_to do |format|
      if @business_category.save
       
        format.html { redirect_to business_categories_path(), notice: '业务类别已成功创建.' }
        format.json { render json: @business_category, status: :created, location: @business_category }
      else
        format.html { render action: "new" }
        format.json { render json: @business_category.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/business_categories_helper.rb
module BusinessCategoriesHelper
end

app/views/business_categories/edit.html.erb
<div class="narrow-center-page">

<%= render_cell(
  :page_title,
  :show,
  data: {
    name: "#{t('model.edit', model: BusinessCategory.model_name.human)} <small>#{t('simple_form.required.text') }</small>",
    toolbar:
    {
      left:
      [
        render_cell(
          :button,
          :show,
          data:
          {
            name: fa_icon('level-up rotate-270'),
            url: business_categories_path,
            options:
            {
              class: 'btn',
              rel: 'tooltip',
              title: "#{t('labels.back_to')}#{t('model.list', :model => BusinessCategory.model_name.human)}",
            }
          }
        )
      ]
    }
  }
) %>


<%= simple_form_for(@business_category , :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name_cn, required: true%>
    <div class="control-group string required business_category_name_cn"><label class="string required control-label" for="business_category_name_cn"><abbr title="选择上一级类别，如无上一级类别请选'无上一级类别'">*</abbr> 上一级类别</label><div class="controls">
      <select class="string required" id="business_category_parent_id" name="business_category[parent_id]">
        <option value="0">无上一级类别</option>
        <%- if @first_categories %>
          <% @first_categories.each do |c|%>
             <option value="<%= c.id%>" <%= @business_category.parent_id.to_i == c.id ? 'selected' : ''%>><%= c.name_cn%></option>
          <% end %>
        <% end %>
      </select></div></div>
       <div class="control-group string required business_category_name_cn"><label class="string required control-label" for="business_category_name_cn"><abbr title="带*星号的为必填项">*</abbr> 是否在供应商列表中显示</label><div class="controls">
      <select class="string required" id="business_category_is_show" name="business_category[is_show]">
        <option value="0" <%= @business_category.is_show.to_i==0 ? 'selected' : ''%>>否</option>
        <option value="1" <%= @business_category.is_show.to_i==1 ? 'selected' : ''%>>是</option>
      </select></div></div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

</div>

app/views/business_categories/index.html.erb
<%= render_cell(
  :page_title,
  :show,
  data:
  {
    name: "#{t('model.list', model: BusinessCategory.model_name.human)}",
    toolbar:
    {
      right:
      [
        (render_cell(
          :button,
          :show,
          data:
          {
            name: fa_icon('plus-sign', text: t('model.create', :model => BusinessCategory.model_name.human)),
            url: new_business_category_path,
            options:
            {
              class: 'btn btn-primary'
            }
          }
        ) if can? :create,BusinessCategory),
        (render_cell(
                :button,
                :show,
                data:
                        {
                                name: fa_icon('plus-sign', text: t('创建类别规格')),
                                url: new_specification_path,
                                options:
                                        {
                                                class: 'btn btn-primary'
                                        }
                        }
        ) if can? :create,BusinessCategory)
      ]
    }
  }
) %>

<%= grid(@business_categories, :show_filters => :when_filtered) do |g|

  g.column name: t('activerecord.attributes.business_category.name_cn'),:class=>"th_style"  do |c|
    c.name_cn
  end

  g.column name: t('activerecord.attributes.business_category.parent_id'),:class=>"th_style" do |c|
    c.parent_name
  end

  g.column name: t('该类别规格') do |c|
    c.children.inject([]){|list, u| list << content_tag(:span, u.name_cn, class: 'label label-success')}.join(' ').html_safe

  end


  if can? :update,BusinessCategory
    g.column :html => {class: 'btn-cell'} do |c|
      link_to(icon('icon-edit'), edit_business_category_path(c), :class => 'btn', :rel => 'tooltip', :title => t('buttons.edit'))
    end
  end

  if can? :destroy,BusinessCategory
    g.column :html => {class: 'btn-cell'} do |c|
      link_to(icon('icon-trash'), business_category_path(c), :method => :delete, :confirm => '你确定要删除这个类别么？', :class => 'btn btn-danger', :rel => 'tooltip', :title => t('buttons.delete'))
    end
  end



end -%>
<style>
  .th_style{
      width: 110px;
  }
</style>

app/views/business_categories/new.html.erb
<div class="narrow-center-page">

<%= render_cell(
  :page_title,
  :show,
  data: {
    name: "#{t('model.create', model: BusinessCategory.model_name.human)} <small>#{t('simple_form.required.text') }</small>",
    toolbar:
    {
      left:
      [
        render_cell(
          :button,
          :show,
          data:
          {
            name: fa_icon('level-up rotate-270'),
            url: business_categories_path,
            options:
            {
              class: 'btn',
              rel: 'tooltip',
              title: "#{t('labels.back_to')}#{t('model.list', :model => BusinessCategory.model_name.human)}",
            }
          }
        )
      ]
    }
  }
) %>


<%= simple_form_for(@business_category , :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name_cn, required: true%>
    <div class="control-group string required business_category_name_cn"><label class="string required control-label" for="business_category_name_cn"><abbr title="选择上一级类别，如无上一级类别请选'无上一级类别'">*</abbr> 上一级类别</label><div class="controls">
      <select class="string required" id="business_category_parent_id" name="business_category[parent_id]">
        <option value="0">无上一级类别</option>
        <%- if @first_categories %>
          <% @first_categories.each do |c|%>
             <option value="<%= c.id%>"><%= c.name_cn%></option>
          <% end %>
        <% end %>
      </select></div></div>
       <div class="control-group string required business_category_name_cn"><label class="string required control-label" for="business_category_name_cn"><abbr title="带*星号的为必填项">*</abbr> 是否在供应商列表中显示</label><div class="controls">
      <select class="string required" id="business_category_is_show" name="business_category[is_show]">
        <option value="0">否</option>
        <option value="1">是</option>
      </select></div></div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

</div>