config/routes.rb
Nix::Application.routes.draw do
  get "dashboard/index"

  devise_for :users

  scope "/admin" do
    resources :users, :roles
  end
  post 'suppliers/generate_spot_plan' => 'suppliers#generate_spot_plan', as: :generate_spot_plan
  post 'suppliers/generate_spot_plan_template' => 'suppliers#generate_spot_plan_template', as: :generate_spot_plan_template
  get 'suppliers/upload_spot_plan' => 'suppliers#upload_spot_plan', as: :upload_spot_plan
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/start' => 'projects#start', as: :start_project
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/save_project_users' => 'projects#save_project_users', as: :save_project_users
  get 'clients/:id/assign_user' => 'clients#assign_user', as: :assign_client_user
  post 'clients/:id/save_client_users' => 'clients#save_client_users', as: :save_client_users
  post 'orders/:id/finish' => 'orders#finish', as: :finish_order
  post 'projects/download_project_info/:id' => 'projects#download_project_info', as: :download_project_info
  post 'web_site_media_reporters/download_reporter_info' => 'web_site_media_reporters#download_reporter_info', as: :download_reporter_info
  get 'web_site_media_reporters/upload_reporter_info' => 'web_site_media_reporters#upload_reporter_info', as: :upload_reporter_info
  post 'fashion_media_infos/download_media_info' => 'fashion_media_infos#download_media_info', as: :download_media_info
  get 'fashion_media_infos/upload_media_info' => 'fashion_media_infos#upload_media_info', as: :upload_media_info
  post 'traveling_photography_media_infos/download_traveling_photography_media_info' => 'traveling_photography_media_infos#download_traveling_photography_media_info', as: :download_traveling_photography_media_info
  get 'traveling_photography_media_infos/upload_traveling_photography_media_info' => 'traveling_photography_media_infos#upload_traveling_photography_media_info', as: :upload_traveling_photography_media_info
  post 'network_opinion_leader_bloggers/download_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#download_network_opinion_leader_blogger', as: :download_network_opinion_leader_blogger
  get 'network_opinion_leader_bloggers/upload_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#upload_network_opinion_leader_blogger', as: :upload_network_opinion_leader_blogger
  post 'grass_resources/download_grass_resource' => 'grass_resources#download_grass_resource', as: :download_grass_resource
  get 'grass_resources/upload_grass_resource' => 'grass_resources#upload_grass_resource', as: :upload_grass_resource
  post 'grass_resources/download_grass_resource_template' => 'grass_resources#download_grass_resource_template', as: :download_grass_resource_template
  post 'moderators/download_moderator' => 'moderators#download_moderator', as: :download_moderator
  get 'moderators/upload_moderator' => 'moderators#upload_moderator', as: :upload_moderator
  get 'file_categories/upload_file_category' => 'file_categories#upload_file_category', as: :upload_file_category
  post 'file_categories/download_file/:id' => 'file_categories#download_file', as: :download_file

  resources :business_categories do
    resources :suppliers
  end
  resources :clients do
    resources :projects do
      resources :orders
    end
  end
  resources :projects do
    resources :file_categories
  end

  resources :suppliers do
    resources :supplier_evaluations
  end
  resources :suppliers,:clients,:projects,:orders,:departments,:network_opinion_leader_bloggers,:moderators,:grass_resources
  resources :business_categories,:supplier_evaluations,:web_site_media_reporters,:fashion_media_infos,:traveling_photography_media_infos,:specifications
  root to: 'dashboard#index', as: :dashboard

  match ':controller(/:action(/:id))(.:format)'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :name, :budget, :started_at, :ended_at, :client_id, :created_by,:user_ids
  validates :name, presence: true
  validates :budget, presence: true
  validates :budget, numericality: { greater_than: 0 }
  validates :started_at, presence: true
  validates :ended_at, presence: true
  belongs_to :client
  has_many :orders

  scope :started, where(is_started: 1)

  def is_started?
    self.is_started.to_i==1
  end

  def started_at_label
    if self.started_at.blank?
      ''
    else
      self.started_at.strftime('%Y-%m-%d')
    end
  end

  def ended_at_label
    if self.ended_at.blank?
      ''
    else
      self.ended_at.strftime('%Y-%m-%d')
    end
  end

  def get_order_info
    info = {}
    _orders = self.orders
    unless _orders.blank?
      _orders.each do |o|
        info[:all_order_price] = info[:all_order_price].to_f+o.all_price.to_f
        info[:all_order_count] =info[:all_order_count].to_i+1
        if o.is_finished?
          info[:finished_order_price] =info[:finished_order_price].to_f+ o.all_price.to_f
          info[:finished_order_count] =info[:finished_order_count].to_i+1
        end
      end
    end
    info
  end


  def self.create_new_template(project=nil)
    return if project==nil
    temp_folder_name = Rails.root.to_s + "/public/temp/"
    unless File.exist?(temp_folder_name)
      FileUtils.mkdir_p(temp_folder_name)
    end
    FileUtils.rm Dir[temp_folder_name.to_s+'*.xls']
    require "spreadsheet"
    workbook = Spreadsheet::Workbook.new

    sheet1 = workbook.create_worksheet(:name => '项目信息')
    sheet1.row(0).replace ['项目名称',project.name.to_s]
    sheet1.row(1).replace ['开始日期',(project.started_at.blank? ? '' : project.started_at.strftime('%Y-%m-%d'))]
    sheet1.row(2).replace ['结束日期',(project.ended_at.blank? ? '' : project.ended_at.strftime('%Y-%m-%d'))]
    sheet1.row(3).replace ['预算', project.budget.to_s]
    if project.is_started?
      sheet1.row(4).replace ['是否已启动','已启动','启动时间',(project.is_started? ? project.is_started_at.strftime('%Y-%m-%d %H:%M:%S') : '')]
    else
      sheet1.row(4).replace ['是否已启动','未启动']
    end
    sheet1.row(5).replace ['执行人员',(project.users.blank? ? '' : project.users.map{|u|u.name}.join(','))]


    _business_categories = BusinessCategory.where('id in (?)',project.category_ids.uniq)
    _orders = project.orders
    unless _business_categories.blank?
      format = Spreadsheet::Format.new(:pattern => 1,:color => :white, :weight => :bold, :size => 11)
      _business_categories.each do |cat|
         cat_sheet =  workbook.create_worksheet(:name => cat.name_cn)
         cat_sheet.row(0).default_format = format
         cat_sheet.row(0).replace ['名称','供应商名称','联系人','联系方式','价格','是否完成','完成时间','备注','创建人','创建时间','更新人','更新时间']
         cat_sheet.row(0).height = 18

        _cat_orders = _orders.select{|_o| _o.business_category_id == cat.id}
        unless  _cat_orders.blank?
          _cat_orders.each_with_index do |c_order,i|
            if c_order.supplier.blank?
              cat_sheet.row(i+1).replace [c_order.name,
                                          '',
                                          '',
                                          '',
                                          c_order.price.to_s,
                                          (c_order.is_finished? ? '已完成' : '未完成'),
                                          (c_order.finished_at.blank? ? '' : c_order.finished_at.strftime('%Y-%m-%d %H:%M:%S')),
                                          c_order.notes,
                                          c_order.created_name,
                                          (c_order.created_at.blank? ? '' : c_order.created_at.strftime('%Y-%m-%d')),
                                          c_order.updated_name,
                                          (c_order.updated_at.blank? ? '' : c_order.updated_at.strftime('%Y-%m-%d'))]
            else
            end
            cat_sheet.row(i+1).replace [c_order.name,
                                        c_order.supplier.name,
                                        c_order.supplier.contact_name,
                                        c_order.supplier.contact_way,
                                        c_order.price.to_s,
                                        (c_order.is_finished? ? '已完成' : '未完成'),
                                        (c_order.finished_at.blank? ? '' : c_order.finished_at.strftime('%Y-%m-%d %H:%M:%S')),
                                        c_order.notes,
                                        c_order.created_name,
                                        (c_order.created_at.blank? ? '' : c_order.created_at.strftime('%Y-%m-%d')),
                                        c_order.updated_name,
                                        (c_order.updated_at.blank? ? '' : c_order.updated_at.strftime('%Y-%m-%d'))]
          end
        end

      end
    end






    new_file = temp_folder_name + project.name.to_s+".xls"
    File.delete(new_file) if File.exist?(new_file)
    workbook.write new_file
    new_file
  end

  def self.test
    require 'yaml'
    return {'未完成'=>1,2=>'123'}.to_yaml
  end

  def category_ids
    if self.orders.blank?
      [0]
    else
      self.orders.map{|o|o.business_category_id}
    end
  end

  def valid1?
    if self.started_at and self.ended_at and self.started_at >= self.ended_at
      errors.add(:ended_at,"结束日期不能小于开始日期")
    end
    errors.size == 0
  end

  def start!
    if self.is_started == 0
      self.is_started = 1
      self.is_started_at = Time.now
      self.save!
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :has_login
  #add_breadcrumb(I18n.t('model.list', model: Client.model_name.human), :clients_path, only: :index)
  add_breadcrumb(I18n.t('model.list', model: Client.model_name.human), :clients_path)

  # GET /projects
  # GET /projects.json
  def index
    @client = Client.find params[:client_id]
    add_breadcrumb("#{@client.name} #{t('model.list', model: Project.model_name.human)}")
    @projects_grid = initialize_grid(Project.where(client_id: params[:client_id]))

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects_grid }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @project.client_id = params[:client_id]
    @project.created_by = current_user.id


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  def show
    @project = Project.find(params[:id])
    @orders_grid = initialize_grid(Order.where('project_id = ?',@project.id).order('is_finished asc'))
    @order_info = @project.get_order_info
    add_breadcrumb("#{@project.client.name} #{t('model.list', model: Project.model_name.human)}",client_projects_path(@project.client))
    add_breadcrumb("#{@project.name}")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    add_breadcrumb("#{@project.client.name} #{t('model.list', model: Project.model_name.human)}", client_projects_path(client_id: @project.client_id))
    add_breadcrumb(t('model.edit', model: Project.model_name.human))
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    #@project.assigned_users << current_user
    @project.updated_by = current_user.id
    respond_to do |format|
      if @project.valid1? and @project.save
        format.html { redirect_to client_projects_path(client_id: @project.client_id), notice: "成功创建#{Project.model_name.human}" }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign_user
    @project = Project.find params[:id]
    @client = @project.client
  end

  def save_project_users
    @project = Project.find(params[:id])
    if request.post?
      respond_to do |format|
        if @project.update_attributes(params[:project])
          format.html { redirect_to client_projects_path(@project.client), notice: "客户执行人员保存成功！" }
          format.json { head :no_content }
        else
          format.html { render action: "assigns" }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    @project.attributes = params[:project]
    @project.updated_by = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to client_projects_path(client_id: @project.client_id), notice: "成功修改#{Project.model_name.human}" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    client_id = @project.client_id
    @project.destroy

    respond_to do |format|
      format.html { redirect_to client_projects_path(client_id), notice: "成功删除#{Project.model_name.human}" }
      format.json { head :no_content }
    end
  end

  def start
    @project = Project.find params[:id]

    if request.post?
      @project.start!

      respond_to do |format|
        format.html { redirect_to client_projects_path(@project.client_id), notice: "项目 #{@project.name} 启动成功" }
        format.json { head :no_content }
      end
    end
  end

  def download_project_info
    @project = Project.find params[:id]
    new_file = Project.create_new_template(@project)
    send_file new_file, :type => "application/octet-stream", :disposition => "attachment"
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/assign_user.html.erb
<div class="narrow-center-page">

  <%= render_cell(:page_title, :show, data:{name: "<strong>#{@client.name}</strong> #{t('客户执行人员列表')}",
                                            toolbar: {
                                                    left:
                                                            [
                                                                    render_cell(:button, :show, data:
                                                                            {
                                                                                    name: fa_icon('level-up rotate-270'),
                                                                                    url: client_projects_path(@client.id),
                                                                                    options:
                                                                                            {
                                                                                                    class: 'btn',
                                                                                                    rel: 'tooltip',
                                                                                                    title: "#{t('labels.back_to')}#{t('model.list', :model => Project.model_name.human)}",
                                                                                            }
                                                                            })
                                                            ]
                                            }
  })
  %>

  <%= simple_form_for(@project, url: save_project_users_path(@project), method: :post, html: {class: 'form-horizontal'}) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.association :users,
                          :collection => User.all_the_other_users(@client.created_by.to_i).collect{|u| ["#{u.name} (#{u.email})", u.id] },
                          :as => :check_boxes %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
  <% end %>

</div>

app/views/projects/edit.html.erb
<div class="narrow-center-page">

  <%= render_cell(
              :page_title,
              :show,
              data:
                      {
                              name: "#{t('model.edit', model: Project.model_name.human)} <small>#{t('simple_form.required.text') }</small>",
                              toolbar: {
                                      left:
                                              [
                                                      render_cell(
                                                              :button,
                                                              :show,
                                                              data:
                                                                      {
                                                                              name: fa_icon('level-up rotate-270'),
                                                                              url: client_projects_path(@project.client_id),
                                                                              options:
                                                                                      {
                                                                                              class: 'btn',
                                                                                              rel: 'tooltip',
                                                                                              title: "#{t('labels.back_to')}#{t('model.list', :model => Project.model_name.human)}",
                                                                                      }
                                                                      }
                                                      )
                                              ]
                              }
                      }
      )
  %>

  <%= simple_form_for(@project , :html => {:class => 'form-horizontal' }) do |f| %>
      <%= f.error_notification %>


      <div class="form-inputs">
        <%= f.input :name, required: true %>
        <%= f.input :budget, required: true %>
        <%= f.input :started_at, as: :date_picker, required: true %>
        <%= f.input :ended_at, as: :date_picker, required: true %>
        <%= f.input :client_id, as: :hidden %>
        <%= f.input :created_by, as: :hidden %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
  <% end %>


</div>

app/views/projects/index.html.erb
<%= render_cell(:page_title, :show, data:{name: "<strong>#{@client.name}</strong> #{t('model.list', model: Project.model_name.human)}",
                                          toolbar: {
                                                  right:
                                                          [
                                                                  (render_cell(:button, :show, data:
                                                                          {
                                                                                  name: fa_icon('plus-sign', text: t('model.create', :model => Project.model_name.human)),
                                                                                  url: new_client_project_path,
                                                                                  options: {class: 'btn btn-primary'}
                                                                          }) if can? :create,Project),

                                                          ]
                                          }
})
%>

<div class="well">
  客户执行人员：<%= @client.users.inject([]) {|list, u| list << content_tag(:span, u.name, class: 'label label-success')}.join(' ').html_safe %>
  <%= link_to(t('客户执行人员管理'), assign_client_user_path(@client), class: 'btn-small btn-inverse pull-right') if can? :update,Client %>
</div>


<%= grid(@projects_grid, :show_filters => :when_filtered) do |g|

  g.column name: t('activerecord.attributes.project.name') do |project|
    (link_to content_tag(:strong, project.name), project_path(project))+"——"+(link_to '项目资料监控',project_file_categories_path(project))
  end

  g.column name: t('activerecord.attributes.project.started_at') do |project|
    project.started_at.strftime('%Y-%m-%d') if project.started_at
  end

  g.column name: t('activerecord.attributes.project.ended_at') do |project|
    project.ended_at.strftime('%Y-%m-%d') if project.ended_at
  end

  g.column name: t('activerecord.attributes.project.budget') do |project|
    content_tag(:strong, number_to_currency(project.budget, precision: 0, unit: '￥'))
  end

  g.column name: t('activerecord.attributes.project.is_started') do |project|

    fa_icon('ok-sign') if project.is_started?
  end

  g.column name: t('activerecord.attributes.project.is_started_at') do |project|
    project.is_started_at.strftime('%Y-%m-%d %H:%M:%S') if project.is_started?
  end

  g.column name: t('activerecord.attributes.project.assigned_users') do |project|
    project.users.inject([]){|list, u| list << content_tag(:span, u.name, class: 'label label-success')}.join(' ').html_safe
  end

  g.column html: {class: ''} do |project|
    link_to(fa_icon('rocket', text: '启动项目'), start_project_path(project), class: 'btn btn-success', method: :post) if !project.is_started? and can? :update,Project
  end


  g.column html: {class: 'btn-cell'} do |project|
    link_to(fa_icon('user'), assign_project_user_path(id: project), rel: 'tooltip', title: '分配项目', class: 'btn') if can? :update,Project
  end

  g.column html: {class: 'btn-cell'} do |project|
    link_to(fa_icon('edit'), edit_project_path(project), :class => 'btn', :rel => 'tooltip', :title => t('buttons.edit')) if can? :update,Project
  end

  g.column html: {class: 'btn-cell'} do |project|
    link_to(fa_icon('trash'), project_path(project), :method => :delete, :confirm => t("confirms.delete"), :class => 'btn btn-danger', :rel => 'tooltip', :title => t('buttons.delete')) if can? :destroy,Project
  end
end -%>

app/views/projects/show.html.erb
<%= render_cell(
            :page_title,
            :show,
            data:
                    {
                            name: "#{fa_icon('star', text:' ')} #{@project.name}",
                            toolbar:
                                    {
                                            right:
                                                    [
                                                            (render_cell(
                                                                    :button,
                                                                    :show,
                                                                    data:
                                                                            {
                                                                                    name: fa_icon('plus-sign', text: '指定供应商'),
                                                                                    url: new_order_path(project_id:@project.id),
                                                                                    options:
                                                                                            {
                                                                                                    class: 'btn btn-primary'
                                                                                            }
                                                                            }
                                                            ) if can? :create,Order),
                                                            (render_cell(
                                                                    :button,
                                                                    :show,
                                                                    data:
                                                                            {
                                                                                    name: fa_icon('download-alt', text: '下载项目信息'),
                                                                                    url: download_project_info_path(@project.id),
                                                                                    options:
                                                                                            {
                                                                                                    class: 'btn btn-info',
                                                                                                    method: :post
                                                                                            }
                                                                            }
                                                            ))
                                                    ]
                                    }
                    }
    ) %>

<div class="padding">
  <table class="plan-summary" id="master-plan-summary">
    <tbody><tr>
      <th style="width:100px;">项目预算</th>
      <th style="width:180px;">已完成订单/总订单</th>
      <th style="width:180px;">已完成金额/总金额</th>
      <th></th>
    </tr>
    <tr>
      <td><span class="project-budget"><%= number_to_currency(@project.budget, unit: '￥', precision: 0) %></span></td>
      <td>
        <div class="label-group master-plan-value-group">
          <span class="item medium">
            <%= content_tag(
                        :span,
                        @order_info[:finished_order_count].to_i,
                        class: 'medium-net-cost'
                ) %>
          </span>
          <span class="item company">
            <%= content_tag(
                        :span,
                        @order_info[:all_order_count].to_i,
                        class: 'company-net-cost'
                ) %>
          </span>
        </div>
      </td>
      <td>
        <div class="label-group master-plan-value-group">
          <span class="item medium">
            <%= content_tag(
                        :span,
                        number_to_currency(@order_info[:finished_order_price].to_f, precision: 0, unit: '￥'),
                        class: 'medium-net-cost'
                ) %>
          </span>
          <span class="item company">
            <%= content_tag(
                        :span,
                        number_to_currency(@order_info[:all_order_price].to_f, precision: 0, unit: '￥'),
                        class: 'company-net-cost'
                ) %>
          </span>
        </div>
      </td>
      <td></td>
    </tr>
    </tbody></table>
</div>


<%= grid(@orders_grid, :show_filters => :when_filtered) do |g|


  g.column name: t('activerecord.attributes.order.name') do |order|
    order.name
  end

  g.column name: t('activerecord.attributes.order.supplier_name') do |order|
    order.supplier.name if order.supplier
  end

  g.column name: t('activerecord.attributes.supplier.contact_name') do |order|
    order.supplier.contact_name if order.supplier
  end

  g.column name: t('activerecord.attributes.supplier.phone') do |order|
    order.supplier.phone if order.supplier
  end

  g.column name: t('activerecord.attributes.supplier.qq') do |order|
    order.supplier.qq if order.supplier
  end

  g.column name: t('activerecord.attributes.supplier.email') do |order|
    order.supplier.email if order.supplier
  end

  g.column name: t('activerecord.attributes.supplier.spec') do |order|
    order.supplier.spec_name if order.supplier
  end

  g.column name: t('activerecord.attributes.order.price') do |order|
    content_tag(:strong, number_to_currency(order.all_price, precision: 0, unit: '￥'))
  end

  g.column name: t('activerecord.attributes.order.is_finished') do |order|
    order.is_finished? ? fa_icon('ok-sign')+order.finished_at.strftime('%Y-%m-%d %H:%M:%S') : ''
  end

  g.column name: t('activerecord.attributes.order.notes') do |order|
    order.notes
  end

  g.column name: t('activerecord.attributes.order.updated_by') do |order|
    order.updated_name
  end

  g.column name: t('activerecord.attributes.order.updated_at') do |order|
    order.updated_at.strftime('%Y-%m-%d') if order.updated_at
  end

  g.column name: t('activerecord.attributes.order.created_by') do |order|
    order.created_name
  end

  g.column name: t('activerecord.attributes.order.created_at') do |order|
    order.created_at.strftime('%Y-%m-%d') if order.created_at
  end

  g.column html: {class: 'td-finish'} do |order|
    link_to(fa_icon('rocket', text: '完成订单'), finish_order_path(order), class: 'btn btn-success btn-success1', :title => t('buttons.finish'), method: :post) if !order.is_finished?
  end

  g.column :html => {class: 'btn-cell'} do |order|
    link_to(icon('icon-edit'), edit_order_path(order), :class => 'btn', :rel => 'tooltip', :title => t('buttons.edit'))
  end

  g.column :html => {class: 'btn-cell'} do |order|
    link_to(icon('icon-trash'), order_path(order), :method => :delete, :confirm => '确定要删除这个订单么？', :class => 'btn btn-danger', :rel => 'tooltip', :title => t('buttons.delete'))
  end
end -%>

<style>
  .btn-success1 {
      padding: 1px 5px;
  }
  .td-finish{
     width: 75px;
  }
</style>