config/routes.rb
Nix::Application.routes.draw do
  get "dashboard/index"

  devise_for :users

  scope "/admin" do
    resources :users, :roles
  end
  post 'suppliers/generate_spot_plan' => 'suppliers#generate_spot_plan', as: :generate_spot_plan
  post 'suppliers/generate_spot_plan_template' => 'suppliers#generate_spot_plan_template', as: :generate_spot_plan_template
  get 'suppliers/upload_spot_plan' => 'suppliers#upload_spot_plan', as: :upload_spot_plan
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/start' => 'projects#start', as: :start_project
  get 'projects/:id/assign_user' => 'projects#assign_user', as: :assign_project_user
  post 'projects/:id/save_project_users' => 'projects#save_project_users', as: :save_project_users
  get 'clients/:id/assign_user' => 'clients#assign_user', as: :assign_client_user
  post 'clients/:id/save_client_users' => 'clients#save_client_users', as: :save_client_users
  post 'orders/:id/finish' => 'orders#finish', as: :finish_order
  post 'projects/download_project_info/:id' => 'projects#download_project_info', as: :download_project_info
  post 'web_site_media_reporters/download_reporter_info' => 'web_site_media_reporters#download_reporter_info', as: :download_reporter_info
  get 'web_site_media_reporters/upload_reporter_info' => 'web_site_media_reporters#upload_reporter_info', as: :upload_reporter_info
  post 'fashion_media_infos/download_media_info' => 'fashion_media_infos#download_media_info', as: :download_media_info
  get 'fashion_media_infos/upload_media_info' => 'fashion_media_infos#upload_media_info', as: :upload_media_info
  post 'traveling_photography_media_infos/download_traveling_photography_media_info' => 'traveling_photography_media_infos#download_traveling_photography_media_info', as: :download_traveling_photography_media_info
  get 'traveling_photography_media_infos/upload_traveling_photography_media_info' => 'traveling_photography_media_infos#upload_traveling_photography_media_info', as: :upload_traveling_photography_media_info
  post 'network_opinion_leader_bloggers/download_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#download_network_opinion_leader_blogger', as: :download_network_opinion_leader_blogger
  get 'network_opinion_leader_bloggers/upload_network_opinion_leader_blogger' => 'network_opinion_leader_bloggers#upload_network_opinion_leader_blogger', as: :upload_network_opinion_leader_blogger
  post 'grass_resources/download_grass_resource' => 'grass_resources#download_grass_resource', as: :download_grass_resource
  get 'grass_resources/upload_grass_resource' => 'grass_resources#upload_grass_resource', as: :upload_grass_resource
  post 'grass_resources/download_grass_resource_template' => 'grass_resources#download_grass_resource_template', as: :download_grass_resource_template
  post 'moderators/download_moderator' => 'moderators#download_moderator', as: :download_moderator
  get 'moderators/upload_moderator' => 'moderators#upload_moderator', as: :upload_moderator
  get 'file_categories/upload_file_category' => 'file_categories#upload_file_category', as: :upload_file_category
  post 'file_categories/download_file/:id' => 'file_categories#download_file', as: :download_file

  resources :business_categories do
    resources :suppliers
  end
  resources :clients do
    resources :projects do
      resources :orders
    end
  end
  resources :projects do
    resources :file_categories
  end

  resources :suppliers do
    resources :supplier_evaluations
  end
  resources :suppliers,:clients,:projects,:orders,:departments,:network_opinion_leader_bloggers,:moderators,:grass_resources
  resources :business_categories,:supplier_evaluations,:web_site_media_reporters,:fashion_media_infos,:traveling_photography_media_infos,:specifications
  root to: 'dashboard#index', as: :dashboard

  match ':controller(/:action(/:id))(.:format)'
end

app/models/traveling_photography_media_info.rb
class TravelingPhotographyMediaInfo < ActiveRecord::Base
  attr_accessible :web_site,  :web_site_introduction,  :content_name,  :position,  :mobile,  :email,  :address,  :coverage,:notes,:sex,:man, :woman,:qq
  belongs_to :created_man, :class_name => "User", :foreign_key => "created_by"
  belongs_to :updated_man, :class_name => "User", :foreign_key => "updated_by"
  validates :web_site, presence: {message:'网站不能为空！'}
  validates :web_site_introduction, presence: {message:'网站介绍不能为空！'}
  validates :content_name, presence: {message:'联系人不能为空！'}
  validates :position, presence: {message:'职位不能为空！'}
  validates :address, presence: {message:'地址不能为空！'}
  validates :coverage, presence: {message:'日均覆盖人数不能为空！'}
  validates :man, presence: {message:'日均覆盖人数(男)不能为空！'}
  validates :woman, presence: {message:'日均覆盖人数(女)不能为空！'}
  validates :woman, numericality: { greater_than: 0 }
  validates :man, numericality: { greater_than: 0 }
  validates :coverage, numericality: { greater_than: 0 }

  def other_valid?
    if self.mobile.blank? and self.qq.blank? and self.email.blank?
      errors.add(:mobile,"3种联系方式不能同时为空！")
      errors.add(:qq,"3种联系方式不能同时为空！")
      errors.add(:email,"3种联系方式不能同时为空！")
    end
    if (self.man.to_f+self.woman.to_f)>self.coverage.to_f
      errors.add(:man,"日均覆盖人数男女综合不能超过日均覆盖总人数！")
      errors.add(:woman,"日均覆盖人数男女综合不能超过日均覆盖总人数！")
    end
    errors.size == 0
  end


  def created_name
    self.created_man.blank? ? '' : self.created_man.name
  end
  def updated_name
    self.updated_man.blank? ? '' : self.updated_man.name
  end

  def self.create_new_template(data=nil)
    temp_folder_name = Rails.root.to_s + "/public/temp/"
    unless File.exist?(temp_folder_name)
      FileUtils.mkdir_p(temp_folder_name)
    end
    FileUtils.rm Dir[temp_folder_name.to_s+'*.xls']
    require "spreadsheet"
    workbook = Spreadsheet::Workbook.new

    sheet1 = workbook.create_worksheet(:name => '旅游摄影媒体信息')
    format = Spreadsheet::Format.new(:color => :black,:horizontal_align => :center,:pattern_fg_color=>'silver',:pattern=>1, :size => 10,:border_color=>:black,:border=>:thin)
    sheet1.row(0).default_format = format
    sheet1.row(0).replace ['ID','网站','网站介绍 ','联系人 ','职位 ','电话 ','邮箱 ','QQ','地址 ','日均覆盖人数(万人) ','男','女','备注 ','创建时间 ','创建人 ','更新时间 ','创建人']
    [2,3,4,8,9,10,11].each do |index|
      sheet1.row(0).set_format(index,Spreadsheet::Format.new(:color => :red,:horizontal_align => :center,:pattern_fg_color=>'silver',:pattern=>1, :size => 10,:border_color=>:black,:border=>:thin))
    end
    [5,6,7].each do |index|
      sheet1.row(0).set_format(index,Spreadsheet::Format.new(:color => :blue,:horizontal_align => :center,:pattern_fg_color=>'silver',:pattern=>1, :size => 10,:border_color=>:black,:border=>:thin))
    end
    sheet2 = workbook.create_worksheet(:name => '旅游摄影媒体Excel说明')
    sheet2.row(0).replace ["1.下载的时尚媒体信息列表可以直接进行上传，其中如果填写ID则表示对该条已有数据进行修改，如果没有填写ID则代表是增加一条新的供应商记录。"]
    sheet2.row(1).replace ["2.\"创建时间\",\"创建人\",\"更新时间\",\"更新人\"四项系统会自动生成，可不用填写。"]
    sheet2.row(2).replace ['3.下载旅游/摄影媒体Excel是根据你所提供的查询条件，如果想下载全部供应商则请去掉所有查询条件。']
    sheet2.row(3).replace ['4.如有其他问题请联系 于洋(创意部) QQ:234016483 电话:18641013958']
    sheet2.row(4).replace ["5.上传数据库请注意，红字为必填项，必须填写，蓝色项中必须填写一项。"]
    unless data.blank?
      data.each_with_index do |d,i|

        sheet1.row(i+1).replace [d.id.to_s,
                                 d.web_site,
                                 d.web_site_introduction,
                                 d.content_name,
                                 d.position,
                                 d.mobile,
                                 d.email,
                                 d.qq,
                                 d.address,
                                 d.coverage,
                                 d.man,
                                 d.woman,
                                 d.notes,
                                 d.created_at.strftime('%Y-%m-%d'),
                                 d.created_name,
                                 d.updated_at.strftime('%Y-%m-%d'),
                                 d.updated_name]
      end
    end

    new_file = temp_folder_name + "媒体资源库-旅游摄影媒体信息.xls"
    File.delete(new_file) if File.exist?(new_file)
    workbook.write new_file
    new_file
  end

  def self.create_by_excel(_sheet=nil,user=nil)
    _error_info = ''
    _error_info = '上传文件错误，请重新上传！' if _sheet.nil? or user.nil?
    ActiveRecord::Base.transaction do
      _sheet.each_with_index do |row,index|
        next if index==0
        next if index==1
        break if row.blank?
        if row[0].to_s.strip.blank?
          _data = TravelingPhotographyMediaInfo.new()
        else
          _data = TravelingPhotographyMediaInfo.find_by_id(row[0].to_s.to_i)
          if _data.blank?
            _error_info = 'ID错误，在第'+(index+1).to_s+'行' if _data.blank?
            break
          end
        end

        if row[1].to_s.strip.blank?
          _error_info = '网站不能为空！，在第'+(index+1).to_s+'行'
          break
        else
          _data.web_site = row[1].to_s.strip
        end

        if row[2].to_s.strip.blank?
          _error_info = '网站介绍不能为空！，在第'+(index+1).to_s+'行'
          break
        else
          _data.web_site_introduction = row[2].to_s.strip
        end

        if row[3].to_s.strip.blank?
          _error_info = '联系人不能为空！，在第'+(index+1).to_s+'行'
          break
        else
          _data.content_name = row[3].to_s.strip
        end

        if row[4].to_s.strip.blank?
          _error_info = '职位不能为空！，在第'+(index+1).to_s+'行'
          break
        else
          _data.position = row[4].to_s.strip
        end

        if row[5].to_s.strip.blank? and row[6].to_s.strip.blank?
          _error_info = '电话，Email 不能同时为空！，在第'+(index+1).to_s+'行'
          break
        else
          _data.mobile = row[5].to_s.strip
          _data.email = row[6].to_s.strip
        end

        if row[7].to_s.strip.blank?
          _error_info = '地址不能为空！，在第'+(index+1).to_s+'行'
          break
        else
          _data.address = row[7].to_s.strip
        end

        if row[8].to_s.strip.blank?
          _error_info = '日均覆盖人数不能为空！，在第'+(index+1).to_s+'行'
          break
        else
          _data.coverage = row[8].to_s.strip
        end

        # if row[10].to_s.strip.blank?
        #   _error_info = '日均覆盖人数（男）不能为空！，在第'+(index+1).to_s+'行'
        #   break
        # else
        #   _data.man = row[9].to_s.strip
        # end
        #
        # if row[11].to_s.strip.blank?
        #   _error_info = '日均覆盖人数（女）不能为空！，在第'+(index+1).to_s+'行'
        #   break
        # else
        #   _data.woman = row[10].to_s.strip
        # end
        _data.man = row[9].to_s.strip
        _data.woman = row[10].to_s.strip

        # if (row[11].to_f+row[10].to_f)>row[9].to_f
        #   _error_info = '日均覆盖男人数与女人数之和不能大于日均覆盖人数！，在第'+(index+1).to_s+'行'
        #   break
        # end

        _data.notes=row[11]

        _data.created_at=Time.now
        _data.updated_at=Time.now
        _data.created_by=user.id
        _data.updated_by=user.id
        _data.deleted=0
        _data.save

      end
      if _error_info != ''
        raise ActiveRecord::Rollback
      end
    end
    _error_info
  end
end

app/controllers/traveling_photography_media_infos_controller.rb
class TravelingPhotographyMediaInfosController < ApplicationController

  before_filter :has_login
  add_breadcrumb(I18n.t('model.list', model: TravelingPhotographyMediaInfo.model_name.human), :traveling_photography_media_infos_path, except: :index)
  def index
    sql,sql_attr=' deleted=0',[]

    unless params[:web_site].blank?
      sql += " and web_site like ? "
      sql_attr << "%"+params[:web_site]+"%"
    end

    unless params[:content_name].blank?
      sql += " and content_name like ? "
      sql_attr << "%"+params[:content_name]+"%"
    end

    unless params[:position].blank?
      sql += " and position like ? "
      sql_attr << "%"+params[:position]+"%"
    end

    unless params[:mobile].blank?
      sql += " and mobile like ? "
      sql_attr << "%"+params[:mobile]+"%"
    end

    unless params[:email].blank?
      sql += " and email like ? "
      sql_attr << "%"+params[:email]+"%"
    end

    unless params[:coverage].blank?
      sql += " and coverage >= ? "
      sql_attr << params[:coverage].to_f
    end

    unless params[:coverage1].blank?
      sql += " and coverage <= ? "
      sql_attr << params[:coverage1].to_f
    end

    @medias_grid = initialize_grid(TravelingPhotographyMediaInfo.where([sql]+sql_attr))
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medias_grid }
    end
  end

  def new
    @media = TravelingPhotographyMediaInfo.new()
    @media.created_by = current_user.id
    @cities = City.all(:order=>'province_id asc')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @media }
    end
  end

  def create
    @media = TravelingPhotographyMediaInfo.new(params[:traveling_photography_media_info])

    @media.updated_by = current_user.id
    @media.created_by = current_user.id

    respond_to do |format|
      if @media.other_valid? and @media.save
        format.html { redirect_to traveling_photography_media_infos_path, notice: "成功创建#{TravelingPhotographyMediaInfo.model_name.human}" }
        format.json { render json: @media, status: :created, location: @media }
      else
        format.html { render action: "new" }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @media = TravelingPhotographyMediaInfo.find(params[:id])
  end

  def update
    @media = TravelingPhotographyMediaInfo.find(params[:id])
    @media.attributes=params[:traveling_photography_media_info]
    @media.updated_by = current_user.id
    respond_to do |format|
      if @media.other_valid? and @media.save
        format.html { redirect_to traveling_photography_media_infos_path, notice: "成功修改#{TravelingPhotographyMediaInfo.model_name.human}" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @media = TravelingPhotographyMediaInfo.find(params[:id])
    @media.deleted=1

    if @media.save
      respond_to do |format|
        format.html { redirect_to traveling_photography_media_infos_path, notice: "成功删除#{TravelingPhotographyMediaInfo.model_name.human}" }
        format.json { head :no_content }
      end
    end
  end

  def download_traveling_photography_media_info
    sql,sql_attr=' deleted=0',[]

    unless params[:web_site].blank?
      sql += " and web_site like ? "
      sql_attr << "%"+params[:web_site]+"%"
    end

    unless params[:content_name].blank?
      sql += " and content_name like ? "
      sql_attr << "%"+params[:content_name]+"%"
    end

    unless params[:position].blank?
      sql += " and position like ? "
      sql_attr << "%"+params[:position]+"%"
    end

    unless params[:mobile].blank?
      sql += " and mobile like ? "
      sql_attr << "%"+params[:mobile]+"%"
    end

    unless params[:email].blank?
      sql += " and email like ? "
      sql_attr << "%"+params[:email]+"%"
    end

    unless params[:coverage].blank?
      sql += " and coverage >= ? "
      sql_attr << params[:coverage].to_f
    end

    unless params[:coverage1].blank?
      sql += " and coverage <= ? "
      sql_attr << params[:coverage1].to_f
    end


    data = TravelingPhotographyMediaInfo.where([sql]+sql_attr)
    new_file = TravelingPhotographyMediaInfo.create_new_template(data)
    send_file new_file, :type => "application/octet-stream", :disposition => "attachment"
  end

  def upload_traveling_photography_media_info
    if request.post?
      if params[:excel_file].blank?
        render :text => "<script>alert('请选择上传的文件!');history.go(-1);</script>"
      else
        if %w(xls).include?(params[:excel_file].original_filename.to_s.split('.')[-1])
          begin
            new_file_name = upload_file(params[:excel_file], "/public/files/temp/")
            workbook = Spreadsheet.open("#{Rails.root}/public/files/temp/"+new_file_name)

            _sheet = workbook.worksheet(0)
            _error_info = TravelingPhotographyMediaInfo.create_by_excel(_sheet,current_user)
            FileUtils.rm Dir["#{Rails.root}/public/files/temp/*.xls"]
            respond_to do |format|
              if _error_info == ''
                format.html { redirect_to traveling_photography_media_infos_path(), notice: '上传完成！！！' }
                format.json { render json: {}, status: :created, location: {} }
              else
                format.html { redirect_to traveling_photography_media_infos_path(), alert: _error_info }
                format.json { render json: {}, status: :created, location: {} }
              end
            end
          rescue Exception => e
            ActiveRecord::Rollback
            render :text => "<script>alert('#{e.to_s}');history.go(-1);</script>"
            return
          end
        else
          render :text => "<script>alert('格式错误!');history.go(-1);</script>"
        end
      end
    end
  end
end

app/helpers/traveling_photography_media_infos_helper.rb
module TravelingPhotographyMediaInfosHelper
end

app/views/traveling_photography_media_infos/edit.html.erb
<div class="narrow-center-page">

  <%= render_cell(
              :page_title,
              :show,
              data:
                      {
                              name: "#{t('model.edit', model: TravelingPhotographyMediaInfo.model_name.human)} <small>#{t('simple_form.required.text') }</small>",
                              toolbar: {
                                      left:
                                              [
                                                      render_cell(
                                                              :button,
                                                              :show,
                                                              data:
                                                                      {
                                                                              name: fa_icon('level-up rotate-270'),
                                                                              url: traveling_photography_media_infos_path,
                                                                              options:
                                                                                      {
                                                                                              class: 'btn',
                                                                                              rel: 'tooltip',
                                                                                              title: "#{t('labels.back_to')}#{t('model.list', :model => TravelingPhotographyMediaInfo.model_name.human)}",
                                                                                      }
                                                                      }
                                                      )
                                              ]
                              }
                      }
      )
  %>

  <%= simple_form_for(@media , :html => {:class => 'form-horizontal' }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">


        <%= f.input :web_site, required: true %>
        <%= f.input :web_site_introduction, required: true,:as=>:text,input_html: { rows: 5 } %>
        <%= f.input :content_name, required: true %>
        <%= f.input :position, required: true %>
        <%= f.input :mobile, required: false %>
        <%= f.input :email, required: false %>
        <%= f.input :qq, required: false %>
        <%= f.input :address, required: true ,:as=>:text,input_html: { rows: 5 }%>
        <%= f.input :coverage, required: true %>

        <%= f.input :man, required: true %>
        <%= f.input :woman, required: true %>


        <%= f.input :notes, required: false ,:as=>:text,input_html: { rows: 5 }%>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
  <% end %>


</div>

app/views/traveling_photography_media_infos/index.html.erb
<%= form_tag({},:method=>'get') do -%>
<%= render_cell(:page_title, :show, data:{name: "#{t('model.list', model: TravelingPhotographyMediaInfo.model_name.human)}",
                                          toolbar: {
                                                  right:
                                                          [
                                                                  (render_cell(:button, :show, data:
                                                                          {
                                                                                  name: fa_icon('plus-sign', text: t('model.create', :model => TravelingPhotographyMediaInfo.model_name.human)),
                                                                                  url: new_traveling_photography_media_info_path,
                                                                                  options: {class: 'btn btn-primary'}
                                                                          }) if can? :create,TravelingPhotographyMediaInfo),
                                                                  (render_cell(
                                                                          :button,
                                                                          :show,
                                                                          data:
                                                                                  {
                                                                                          name: fa_icon('cloud-upload', text: t('model.upload', model: TravelingPhotographyMediaInfo.model_name.human)),
                                                                                          url: upload_traveling_photography_media_info_path,
                                                                                          options: {class: 'btn btn-success'}
                                                                                  }
                                                                  ) if can? :create,TravelingPhotographyMediaInfo or can? :update,TravelingPhotographyMediaInfo),
                                                                  render_cell(:button, :show,
                                                                              data:
                                                                                      {
                                                                                              name: fa_icon('download-alt', text: t('model.download',:model => TravelingPhotographyMediaInfo.model_name.human)),
                                                                                              url: download_traveling_photography_media_info_path(params),
                                                                                              options:
                                                                                                      {
                                                                                                              class: 'btn btn-info',
                                                                                                              method: :post
                                                                                                      }
                                                                                      }
                                                                  )

                                                          ]
                                          }
})
%>

<div class="well">


      网站：
      <%= text_field_tag 'web_site',params[:web_site],:style=>"width:100px"-%>
      联系人:
      <%= text_field_tag 'content_name',params[:content_name],:style=>"width:60px"-%>
      职位:
      <%= text_field_tag 'position',params[:position],:style=>"width:100px"-%>
      电话:
      <%= text_field_tag 'mobile',params[:mobile],:style=>"width:100px"-%>
      邮箱:
      <%= text_field_tag 'email',params[:email],:style=>"width:100px"-%>
      日均覆盖人数:
      <%= text_field_tag 'coverage',params[:coverage],:style=>"width:50px"-%>万人 到
      <%= text_field_tag 'coverage1',params[:coverage1],:style=>"width:50px"-%>万人
      <%= submit_tag('查询') -%>

</div>
            <% end -%>

<%= grid(@medias_grid, :show_filters => :when_filtered,:class=> 'tablestyle') do |g|

  g.column name: t('activerecord.attributes.traveling_photography_media_info.web_site') do |m|
    m.web_site
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.web_site_introduction'),:class=>'td_style' do |m|
    m.web_site_introduction
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.content_name') do |m|
    m.content_name
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.position') do |m|
    m.position
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.mobile') do |m|
    m.mobile
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.email') do |m|
    m.email
  end

  g.column name: t('activerecord.attributes.traveling_photography_media_info.address') do |m|
    m.address
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.coverage') do |m|
    m.coverage
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.man') do |m|
    m.man
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.woman') do |m|
    m.woman
  end
  g.column name: t('activerecord.attributes.traveling_photography_media_info.notes') do |m|
    m.notes
  end

  g.column name: t('activerecord.attributes.traveling_photography_media_info.updated_by') do |m|
    m.updated_name
  end

  g.column name: t('activerecord.attributes.traveling_photography_media_info.created_by') do |m|
    m.created_name
  end

  if can? :update,TravelingPhotographyMediaInfo
    g.column html: {class: 'btn-cell'} do |p|
      link_to(fa_icon('edit'), edit_traveling_photography_media_info_path(p), :class => 'btn', :rel => 'tooltip', :title => t('buttons.edit'))
    end
  end

  if can? :destroy,TravelingPhotographyMediaInfo
    g.column html: {class: 'btn-cell'} do |p|
      link_to(fa_icon('trash'), traveling_photography_media_info_path(p), :method => :delete, :confirm => t("confirms.delete"), :class => 'btn btn-danger', :rel => 'tooltip', :title => t('buttons.delete'))
    end
  end

end -%>
<style type="text/css">
    .tablestyle{
        width: 3000px;
    }

    #grid{
        overflow: auto;
    }
    .td_style{
        width: 750px;
    }

</style>
<script>
    $('#grid').attr('style','height:300px');
</script>

app/views/traveling_photography_media_infos/new.html.erb
<div class="narrow-center-page">

  <%= render_cell(
              :page_title,
              :show,
              data:
                      {
                              name: "#{t('model.create', model: TravelingPhotographyMediaInfo.model_name.human)} <small>#{t('simple_form.required.text') }</small>",
                              toolbar: {
                                      left:
                                              [
                                                      render_cell(
                                                              :button,
                                                              :show,
                                                              data:
                                                                      {
                                                                              name: fa_icon('level-up rotate-270'),
                                                                              url: traveling_photography_media_infos_path,
                                                                              options:
                                                                                      {
                                                                                              class: 'btn',
                                                                                              rel: 'tooltip',
                                                                                              title: "#{t('labels.back_to')}#{t('model.list', :model => TravelingPhotographyMediaInfo.model_name.human)}",
                                                                                      }
                                                                      }
                                                      )
                                              ]
                              }
                      }
      )
  %>

  <%= simple_form_for(@media , :html => {:class => 'form-horizontal' }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">


        <%= f.input :web_site, required: true %>
        <%= f.input :web_site_introduction, required: true,:as=>:text,input_html: { rows: 5 } %>
        <%= f.input :content_name, required: true %>
        <%= f.input :position, required: true %>
        <%= f.input :mobile, required: false %>
        <%= f.input :email, required: false %>
        <%= f.input :qq, required: false %>
        <%= f.input :address, required: true ,:as=>:text,input_html: { rows: 5 }%>
        <%= f.input :coverage, required: true %>

        <%= f.input :man, required: true %>
        <%= f.input :woman, required: true %>


        <%= f.input :notes, required: false ,:as=>:text,input_html: { rows: 5 }%>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
  <% end %>


</div>